CREATE TABLE BOOKS
(
  BID          NUMBER,
  BNAME        VARCHAR2(40 BYTE)                NOT NULL,
  BDESC        VARCHAR2(400 BYTE),
  BAUTHOR      VARCHAR2(100 BYTE),
  TOTOFCOP     NUMBER                           DEFAULT 0,
  AVILABILITY  CHAR(1 BYTE),
  TOTAVAIL     NUMBER
);
ALTER TABLE BOOKS ADD (PRIMARY KEY  (BID));